apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-db
  name: vote-db
spec:
  type: ClusterIP
  ports:
  - name: "vote-db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: vote-db
  