apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 5
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: dedaced/voting_app-vote:dc47ef574054ab68f9660d1735f177d4a8e042c0
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafka:9092
          - name: SESSION_API_URL
            value: http://vote-session:8082/sessions
        ports:
        - containerPort: 8080
          name: vote
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          