apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dedaced/voting_app-worker:latest
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafka:9092
          - name: VOTE_DB_URL
            value: jdbc:postgresql://vote-db:5432/cs544