name: Build images and push to registry

on:
  push:
    branches:
      - feat-actions
    paths:
      - 'vote-session/**'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build-vote-session-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./vote-session
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/voting_app-vote-session:${{ github.sha }}
            ${{ env.DOCKERHUB_USERNAME }}/voting_app-vote-session:latest
          build-args: |
            VOTE_DB_URL="jdbc:postgresql://vote-db:5432/cs544"

      - name: Update Kubernetes deployment
        # Replace image tag in deployment.yaml with new Docker image tagged by commit SHA
        run: |
          sed -i "s|image: ${{ env.DOCKERHUB_USERNAME }}/voting_app-vote-session:.*|image: ${{ env.DOCKERHUB_USERNAME }}/voting_app-vote-session:${{ github.sha }}|g" k8s-specifications/vote-session-deployment.yaml
          echo "Updated image in k8s-specifications/vote-session-deployment.yaml"
      
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8s-specifications/vote-session-deployment.yaml
          git commit -m "Update vote-session deployment image to ${{ env.DOCKERHUB_USERNAME }}/voting_app-vote-session:${{ github.sha }}"
          git pull origin feat-actions --rebase || true
          git push origin feat-actions
  