name: Integrate result app

on:
  push:
    branches:
      - main
    paths:
      - 'result/**'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build-result-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./result
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/voting_app-result:${{ github.sha }}
            ${{ env.DOCKERHUB_USERNAME }}/voting_app-result:latest
          build-args: |
            VOTE_DB_URL=postgres://postgres:postgres@vote-db/cs544
      - name: Update Kubernetes deployment
        # Replace image tag in deployment.yaml with new Docker image tagged by commit SHA
        run: |
          sed -i "s|image: ${{ env.DOCKERHUB_USERNAME }}/voting_app-result:.*|image: ${{ env.DOCKERHUB_USERNAME }}/voting_app-result:${{ github.sha }}|g" k8s-specifications/result-deployment.yaml
          echo "Updated image in k8s-specifications/result-deployment.yaml"
      
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8s-specifications/result-deployment.yaml
          git commit -m "Update result deployment image to ${{ env.DOCKERHUB_USERNAME }}/voting_app-result:${{ github.sha }}"
          git pull origin main --rebase || false
          git push origin main
  