name: Build images and push to registry

# TODO: Detect only changed subproject and build only that image

on:
  push:
    branches:
      - feat-actions

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build-result-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [vote, result, vote-session, worker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Detect changes
        id: changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: steps.changes.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/voting_app-${{ matrix.service }}:${{ github.sha }}
            ${{ env.DOCKERHUB_USERNAME }}/voting_app-${{ matrix.service }}:latest
          build-args: |
            VOTE_DB_URL=postgres://postgres:postgres@vote-db/cs544

      - name: Update Kubernetes deployment
        # Replace image tag in deployment.yaml with new Docker image tagged by commit SHA
        run: |
          sed -i "s|image: ${{ env.DOCKERHUB_USERNAME }}/voting_app-${{ matrix.service }}:.*|image: ${{ env.DOCKERHUB_USERNAME }}/voting_app-${{ matrix.service }}:${{ github.sha }}|g" k8s-specifications/${{ matrix.service }}-deployment.yaml
          echo "Updated image in k8s-specifications/${{ matrix.service }}-deployment.yaml"
      
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8s-specifications/${{ matrix.service }}-deployment.yaml
          git commit -m "Update ${{ matrix.service }} deployment image to ${{ env.DOCKERHUB_USERNAME }}/voting_app-${{ matrix.service }}:${{ github.sha }}"
          git push origin feat-actions
